[package]
name = "perceive-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "main.rs"
name = "perceive"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"perceive-search" = { path = "../perceive-search" }
tch = "0.10.1"
